version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 3000:3000
    env_file:
      - .env.local
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    env_file:
      - .env.local
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  db:
    driver: local
